### ISSUE TITLE
Use this without NPM involved ?

### ISSUE THREAD

**Issue by zilveer** [nmaro/nicks-gun-utils#1]
Hi,
First of all thanks for all the utilities, they seem to great to use.

I am currently working purely on the client side without any servera involved except for the GUN peer.
Therefor I would like to ask if I can use these functions /libraries without using NPM ?

If so , can you please provide any example where we can use `.put()` `.get()` and get data with and without encrypting / decrypting?
That would be awesome, thanks for any response and once again thanks for all this utilities for GUN DB !

Best regards Zilveer

**Comment by nickredmark** [comment]
Hey @zilveer I recommend you check out the source code, it really isn't too long.
